spring:
  application:
    name: user-server
  config:
    import: optional:configserver:http://localhost:2301
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ratel-user
    username: ratel_user
    password: ratelpswd
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:2302/eureka/

server:
  port: 8084